modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Rollyear/Mechnotury/issue"
updateJSONURL="https://github.com/Rollyear/Mechnotury"

[[mods]]
modId="mechnotury"
version="1.0"
displayName="Mechnotury"
logoFile="logo.png"
credits="Roystain.R,Illusion"
authors="Roystain.R,Illusion"
description='''
你能在机械纪元里找到许多有趣的东西。祝你玩的开心！
You can find tons of interesting things in Mechnotury.Hope you enjoy it!
'''

[[dependencies.mechnotury]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.15.2-1.2-35.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mechnotury]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.2-2.0.2.6,)"
    ordering="NONE"
    side="BOTH"



