modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Rollyear/Mechnotury/issue"
updateJSONURL="https://github.com/Rollyear/Mechnotury"
license="All rights reserved"

[[mods]]
modId="mechnotury"
version="1.0"
displayName="Mechnotury"
logoFile="logo.png"
credits="Roystain.R,Illusion"
authors="Roystain.R,Illusion"
description='''
你能在机械纪元里找到许多有趣的东西。祝你玩的开心！
You can find tons of interesting things in Mechnotury.Hope you enjoy it!
'''

[[dependencies.mechnotury]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="[1.16.4,1.17)"
ordering="NONE"
side="BOTH"



